//this is temporary data
export const INDIA_STATES = [
  { value: "maharashtra", label: "Maharashtra" },
  { value: "uttar pradesh", label: "Uttar Pradesh" },
  { value: "tamil nadu", label: "Tamil Nadu" },
  { value: "karnataka", label: "Karnataka" },
  { value: "delhi", label: "Delhi" },
  { value: "rajasthan", label: "Rajasthan" },
  { value: "gujarat", label: "Gujarat" },
  { value: "punjab", label: "Punjab" },
  { value: "west bengal", label: "West Bengal" },
  { value: "madhya pradesh", label: "Madhya Pradesh" },
];

export const STATE_DISTRICTS = {
  maharashtra: [
    { value: "mumbai", label: "Mumbai" },
    { value: "pune", label: "Pune" },
    { value: "nagpur", label: "Nagpur" },
    { value: "nashik", label: "Nashik" },
    { value: "thane", label: "Thane" },
  ],
  "uttar pradesh": [
    { value: "lucknow", label: "Lucknow" },
    { value: "agra", label: "Agra" },
    { value: "varanasi", label: "Varanasi" },
    { value: "kanpur", label: "Kanpur" },
    { value: "ghaziabad", label: "Ghaziabad" },
  ],
  "tamil nadu": [
    { value: "chennai", label: "Chennai" },
    { value: "coimbatore", label: "Coimbatore" },
    { value: "madurai", label: "Madurai" },
    { value: "salem", label: "Salem" },
    { value: "tirunelveli", label: "Tirunelveli" },
  ],
  karnataka: [
    { value: "bangalore", label: "Bangalore" },
    { value: "mysore", label: "Mysore" },
    { value: "hubli", label: "Hubli" },
    { value: "gulbarga", label: "Gulbarga" },
    { value: "bijapur", label: "Bijapur" },
  ],
  delhi: [
    { value: "new delhi", label: "New Delhi" },
    { value: "south delhi", label: "South Delhi" },
    { value: "east delhi", label: "East Delhi" },
    { value: "west delhi", label: "West Delhi" },
    { value: "north delhi", label: "North Delhi" },
  ],
  rajasthan: [
    { value: "jaipur", label: "Jaipur" },
    { value: "udaipur", label: "Udaipur" },
    { value: "kota", label: "Kota" },
    { value: "ajmer", label: "Ajmer" },
    { value: "bikaner", label: "Bikaner" },
  ],
  gujarat: [
    { value: "ahmedabad", label: "Ahmedabad" },
    { value: "rajkot", label: "Rajkot" },
    { value: "vadodara", label: "Vadodara" },
    { value: "bhavnagar", label: "Bhavnagar" },
    { value: "surat", label: "Surat" },
  ],
  punjab: [
    { value: "ludhiana", label: "Ludhiana" },
    { value: "amritsar", label: "Amritsar" },
    { value: "jalandhar", label: "Jalandhar" },
    { value: "patiala", label: "Patiala" },
    { value: "bathinda", label: "Bathinda" },
  ],
  "west bengal": [
    { value: "kolkata", label: "Kolkata" },
    { value: "darjeeling", label: "Darjeeling" },
    { value: "asansol", label: "Asansol" },
    { value: "siliguri", label: "Siliguri" },
    { value: "howrah", label: "Howrah" },
  ],
  "madhya pradesh": [
    { value: "bhopal", label: "Bhopal" },
    { value: "indore", label: "Indore" },
    { value: "jabalpur", label: "Jabalpur" },
    { value: "gwalior", label: "Gwalior" },
    { value: "rewa", label: "Rewa" },
  ],
};

export const DISTRICT_CITIES = {
  // Maharashtra
  mumbai: [
    { value: "andheri", label: "Andheri" },
    { value: "bandra", label: "Bandra" },
    { value: "colaba", label: "Colaba" },
    { value: "dadar", label: "Dadar" },
    { value: "borivali", label: "Borivali" },
  ],
  pune: [
    { value: "hadapsar", label: "Hadapsar" },
    { value: "kothrud", label: "Kothrud" },
    { value: "shivaji nagar", label: "Shivaji Nagar" },
    { value: "yerawada", label: "Yerawada" },
    { value: "wakad", label: "Wakad" },
  ],
  nagpur: [
    { value: "sitabuldi", label: "Sitabuldi" },
    { value: "dharampeth", label: "Dharampeth" },
    { value: "manish nagar", label: "Manish Nagar" },
    { value: "kamptee", label: "Kamptee" },
    { value: "mahal", label: "Mahal" },
  ],
  nashik: [
    { value: "cidco", label: "Cidco" },
    { value: "vishnu nagar", label: "Vishnu Nagar" },
    { value: "midc", label: "Midc" },
    { value: "hanuman nagar", label: "Hanuman Nagar" },
    { value: "khandeshwar", label: "Khandeshwar" },
  ],
  thane: [
    { value: "bhiwandi", label: "Bhiwandi" },
    { value: "kalyan", label: "Kalyan" },
    { value: "vasai-virar", label: "Vasai-Virar" },
    { value: "mira bhayandar", label: "Mira Bhayandar" },
    { value: "ghansoli", label: "Ghansoli" },
  ],

  // Uttar Pradesh
  lucknow: [
    { value: "alambagh", label: "Alambagh" },
    { value: "chinhat", label: "Chinhat" },
    { value: "hazratganj", label: "Hazratganj" },
    { value: "rajajipuram", label: "Rajajipuram" },
    { value: "telibagh", label: "Telibagh" },
  ],
  agra: [
    { value: "fatehpur sikri", label: "Fatehpur Sikri" },
    { value: "shahganj", label: "Shahganj" },
    { value: "sikandra", label: "Sikandra" },
    { value: "raja ki mandi", label: "Raja Ki Mandi" },
    { value: "bodla", label: "Bodla" },
  ],
  varanasi: [
    { value: "birla", label: "Birla" },
    { value: "lalapura", label: "Lalapura" },
    { value: "dhilapurt", label: "Dhilapurt" },
    { value: "hastipur", label: "Hastipur" },
    { value: "sondhi", label: "Sondhi" },
  ],
  kanpur: [
    { value: "ghatampur", label: "Ghatampur" },
    { value: "panki", label: "Panki" },
    { value: "alambagh", label: "Alambagh" },
    { value: "chakeri", label: "Chakeri" },
    { value: "bithoor", label: "Bithoor" },
  ],
  ghaziabad: [
    { value: "indirapuram", label: "Indirapuram" },
    { value: "vasundhara", label: "Vasundhara" },
    { value: "vijay nagar", label: "Vijay Nagar" },
    { value: "noida sector 62", label: "Noida Sector 62" },
    { value: "kaushambi", label: "Kaushambi" },
  ],

  // Tamil Nadu
  chennai: [
    { value: "t nagar", label: "T. Nagar" },
    { value: "adyar", label: "Adyar" },
    { value: "velachery", label: "Velachery" },
    { value: "kk nagar", label: "KK Nagar" },
    { value: "mylapore", label: "Mylapore" },
  ],
  coimbatore: [
    { value: "pudupet", label: "Pudupet" },
    { value: "athipalayam", label: "Athipalayam" },
    { value: "r s road", label: "R S Road" },
    { value: "wilsontown", label: "Wilsontown" },
  ],
  madurai: [
    { value: "shenbagam", label: "Shenbagam" },
    { value: "tss", label: "TSS" },
    { value: "pss", label: "PSS" },
    { value: "dbs", label: "DBS" },
  ],
  salem: [
    { value: "periyar", label: "Periyar" },
    { value: "rajagopalapuram", label: "Rajagopalapuram" },
    { value: "bavani", label: "Bavani" },
    { value: "masinaikenpalayam", label: "Masinaikenpalayam" },
    { value: "saraswathi nagar", label: "Saraswathi Nagar" },
  ],
  tirunelveli: [
    { value: "sannathi", label: "Sannathi" },
    { value: "wadakkanchery", label: "Wadakkanchery" },
    { value: "vellakovil", label: "Vellakovil" },
    { value: "pudupalayam", label: "Pudupalayam" },
    { value: "tiruvadanai", label: "Tiruvadanai" },
  ],

  // Karnataka
  bangalore: [
    { value: "electronic city", label: "Electronic City" },
    { value: "koramangala", label: "Koramangala" },
    { value: "hsr layout", label: "HSR Layout" },
    { value: "indiranagar", label: "Indiranagar" },
    { value: "mg road", label: "MG Road" },
  ],
  mysore: [
    { value: "north end", label: "North End" },
    { value: "somwarpet", label: "Somwarpet" },
    { value: "hunsur", label: "Hunsur" },
    { value: "bommankoppa", label: "Bommankoppa" },
    { value: "venugopal", label: "Venugopal" },
  ],
  hubli: [
    { value: "gulbarga", label: "Gulbarga" },
    { value: "rannebennur", label: "Rannebennur" },
    { value: "shivamogga", label: "Shivamogga" },
    { value: "yemalur", label: "Yemalur" },
    { value: "ramagondanahalli", label: "Ramagondanahalli" },
  ],
  gulbarga: [
    { value: "aland", label: "Aland" },
    { value: "chincholi", label: "Chincholi" },
    { value: "jevargi", label: "Jevargi" },
    { value: "sudden", label: "Sudden" },
    { value: "shahabad", label: "Shahabad" },
  ],
  bijapur: [
    { value: "sindhanur", label: "Sindhanur" },
    { value: "tappal", label: "Tappal" },
    { value: "raipur", label: "Raipur" },
    { value: "hampi", label: "Hampi" },
  ],

  // Delhi
  "new delhi": [
    { value: "connaught place", label: "Connaught Place" },
    { value: "karol bagh", label: "Karol Bagh" },
    { value: "rk puram", label: "RK Puram" },
    { value: "saket", label: "Saket" },
    { value: "vasant kunj", label: "Vasant Kunj" },
  ],
  "south delhi": [
    { value: "dlf phase 1", label: "DLF Phase 1" },
    { value: "mgf mall", label: "MGF Mall" },
    { value: "vikaspuri", label: "Vikaspuri" },
    { value: "paschim vihar", label: "Paschim Vihar" },
    { value: "jankapuri", label: "Jankapuri" },
  ],
  "east delhi": [
    { value: "anand vihar", label: "Anand Vihar" },
    { value: "noida sector 50", label: "Noida Sector 50" },
    { value: "kalindi kunj", label: "Kalindi Kunj" },
    { value: "rudrapur", label: "Rudrapur" },
    { value: "indrapuram", label: "Indrapuram" },
  ],
  "west delhi": [
    { value: "jambheshwar", label: "Jambheshwar" },
    { value: "bawana", label: "Bawana" },
    { value: "bagewari", label: "Bagewari" },
    { value: "rithala", label: "Rithala" },
    { value: "shadipur", label: "Shadipur" },
  ],
  "north delhi": [
    { value: "kashmere gate", label: "Kashmere Gate" },
    { value: "desh bandhu", label: "Desh Bandhu" },
    { value: "pitampura", label: "Pitampura" },
    { value: "ashok vihar", label: "Ashok Vihar" },
    { value: "rohini sector 5", label: "Rohini Sector 5" },
  ],

  // Rajasthan
  jaipur: [
    { value: "malviya nagar", label: "Malviya Nagar" },
    { value: "tonk road", label: "Tonk Road" },
    { value: "bani park", label: "Bani Park" },
    { value: "jhotwara", label: "Jhotwara" },
    { value: "civil lines", label: "Civil Lines" },
  ],
  udaipur: [
    { value: "malpura", label: "Malpura" },
    { value: "fatehpur", label: "Fatehpur" },
    { value: "sewar", label: "Sewar" },
    { value: "balicha", label: "Balicha" },
  ],
  ajmer: [
    { value: "rajmahal", label: "Rajmahal" },
    { value: "himmat nagar", label: "Himmat Nagar" },
    { value: "purni", label: "Purni" },
    { value: "khazana", label: "Khazana" },
    { value: "nit jaipur", label: "NIT Jaipur" },
  ],
  kota: [
    { value: "nadgaon", label: "Nadgaon" },
    { value: "rathhwell", label: "Rathhwell" },
    { value: "sojati gate", label: "Sojati Gate" },
    { value: "yenote", label: "Yenote" },
    { value: "sumera", label: "Sumera" },
  ],
  // Gujarat
  ahmedabad: [
    { value: "navrangpura", label: "Navrangpura" },
    { value: "satellite", label: "Satellite" },
    { value: "vastrapur", label: "Vastrapur" },
    { value: "maninagar", label: "Maninagar" },
    { value: "cg road", label: "CG Road" },
  ],
  rajkot: [
    { value: "kalavad", label: "Kalavad" },
    { value: "jamnagar", label: "Jamnagar" },
    { value: "gondal", label: "Gondal" },
    { value: "morbi", label: "Morbi" },
    { value: "wankaner", label: "Wankaner" },
  ],
  vadodara: [
    { value: "alkapuri", label: "Alkapuri" },
    { value: "manjalpur", label: "Manjalpur" },
    { value: "fatehgunj", label: "Fatehgunj" },
    { value: "karelibaug", label: "Karelibaug" },
    { value: "gotri", label: "Gotri" },
  ],
  bhavnagar: [
    { value: "talaja", label: "Talaja" },
    { value: "gadhada", label: "Gadhada" },
    { value: "savarkundla", label: "Savarkundla" },
    { value: "mahuva", label: "Mahuva" },
    { value: "palitana", label: "Palitana" },
  ],
  surat: [
    { value: "adajan", label: "Adajan" },
    { value: "varachha", label: "Varachha" },
    { value: "katargam", label: "Katargam" },
    { value: "udhna", label: "Udhna" },
    { value: "puna", label: "Puna" },
  ],

  // Punjab
  ludhiana: [
    { value: "sarabha nagar", label: "Sarabha Nagar" },
    { value: "gill road", label: "Gill Road" },
    { value: "ferozepur road", label: "Ferozepur Road" },
    { value: "chandigarh road", label: "Chandigarh Road" },
    { value: "dugri", label: "Dugri" },
  ],
  amritsar: [
    { value: "ranjit avenue", label: "Ranjit Avenue" },
    { value: "lawrence road", label: "Lawrence Road" },
    { value: "gumti bazaar", label: "Gumti Bazaar" },
    { value: "katra ahluwalia", label: "Katra Ahluwalia" },
    { value: "putlighar", label: "Putlighar" },
  ],
  jalandhar: [
    { value: "nakodar", label: "Nakodar" },
    { value: "phagwara", label: "Phagwara" },
    { value: "kapurthala", label: "Kapurthala" },
    { value: "nurmahal", label: "Nurmahal" },
    { value: "shahkot", label: "Shahkot" },
  ],
  patiala: [
    { value: "samana", label: "Samana" },
    { value: "rajpura", label: "Rajpura" },
    { value: "nabha", label: "Nabha" },
    { value: "shutrana", label: "Shutrana" },
    { value: "ghanaur", label: "Ghanaur" },
  ],
  bathinda: [
    { value: "malout", label: "Malout" },
    { value: "goniana", label: "Goniana" },
    { value: "talwandi sabo", label: "Talwandi Sabo" },
    { value: "maur", label: "Maur" },
    { value: "rampura phul", label: "Rampura Phul" },
  ],

  // West Bengal
  kolkata: [
    { value: "salt lake", label: "Salt Lake" },
    { value: "park street", label: "Park Street" },
    { value: "dum dum", label: "Dum Dum" },
    { value: "behala", label: "Behala" },
    { value: "ballygunge", label: "Ballygunge" },
  ],
  darjeeling: [
    { value: "kurseong", label: "Kurseong" },
    { value: "kalimpong", label: "Kalimpong" },
    { value: "mirik", label: "Mirik" },
    { value: "sukhiapokhri", label: "Sukhiapokhri" },
    { value: "ghoom", label: "Ghoom" },
  ],
  asansol: [
    { value: "durgapur", label: "Durgapur" },
    { value: "barakar", label: "Barakar" },
    { value: "kulti", label: "Kulti" },
    { value: "raniganj", label: "Raniganj" },
    { value: "jamuria", label: "Jamuria" },
  ],
  siliguri: [
    { value: "matigara", label: "Matigara" },
    { value: "bagdogra", label: "Bagdogra" },
    { value: "naxalbari", label: "Naxalbari" },
    { value: "phansidewa", label: "Phansidewa" },
    { value: "kharibari", label: "Kharibari" },
  ],
  howrah: [
    { value: "bally", label: "Bally" },
    { value: "uluberia", label: "Uluberia" },
    { value: "domjur", label: "Domjur" },
    { value: "panchla", label: "Panchla" },
    { value: "sankrail", label: "Sankrail" },
  ],

  // Madhya Pradesh
  bhopal: [
    { value: "koh-e-fiza", label: "Koh-e-Fiza" },
    { value: "shahpura", label: "Shahpura" },
    { value: "kaliasot", label: "Kaliasot" },
    { value: "berasia", label: "Berasia" },
    { value: "govindpura", label: "Govindpura" },
  ],
  indore: [
    { value: "vijay nagar", label: "Vijay Nagar" },
    { value: "rajwada", label: "Rajwada" },
    { value: "palasia", label: "Palasia" },
    { value: "kanadia", label: "Kanadia" },
    { value: "rau", label: "Rau" },
  ],
  jabalpur: [
    { value: "gopalpur", label: "Gopalpur" },
    { value: "katangi", label: "Katangi" },
    { value: "tilwara", label: "Tilwara" },
    { value: "pipariya", label: "Pipariya" },
    { value: "ranjhi", label: "Ranjhi" },
  ],
  gwalior: [
    { value: "lashkar", label: "Lashkar" },
    { value: "morar", label: "Morar" },
    { value: "sirol", label: "Sirol" },
    { value: "bahodapur", label: "Bahodapur" },
    { value: "dabra", label: "Dabra" },
  ],
  rewa: [
    { value: "civil lines", label: "Civil Lines" },
    { value: "gurh", label: "Gurh" },
    { value: "manikwar", label: "Manikwar" },
    { value: "hanumana", label: "Hanumana" },
    { value: "bichiya", label: "Bichiya" },
  ],
};
