export const AREA_OPTIONS = [
  { value: "agra (city)", label: "Agra (City)" },
  { value: "agra (outskirts)", label: "Agra (Outskirts)" },
  { value: "ayodhya", label: "Ayodhya" },
  { value: "bareilly (city)", label: "Bareilly (City)" },
  { value: "bareilly (outskirts)", label: "Bareilly (Outskirts)" },
  { value: "ghaziabad (city)", label: "Ghaziabad (City)" },
  { value: "ghaziabad (outskirts)", label: "Ghaziabad (Outskirts)" },
  { value: "gorakhpur (city)", label: "Gorakhpur (City)" },
  { value: "gorakhpur (outskirts)", label: "Gorakhpur (Outskirts)" },
  { value: "jhansi (city)", label: "Jhansi (City)" },
  { value: "jhansi (outskirts)", label: "Jhansi (Outskirts)" },
  { value: "kanpur", label: "Kanpur" },
  { value: "lucknow (city)", label: "Lucknow (City)" },
  { value: "lucknow (outskirts)", label: "Lucknow (Outskirts)" },
  { value: "prayagraj (city)", label: "Prayagraj (City)" },
  { value: "prayagraj (outskirts)", label: "Prayagraj (Outskirts)" },
  { value: "varanasi (city)", label: "Varanasi (City)" },
  { value: "varanasi (outskirts)", label: "Varanasi (Outskirts)" },
];
