export const COUNTRY_CODES = [
  { value: "+91", label: "🇮🇳 India (+91)" },
  { value: "+1", label: "🇺🇸 USA (+1)" },
  { value: "+44", label: "🇬🇧 UK (+44)" },
  { value: "+971", label: "🇦🇪 UAE (+971)" },
  { value: "+61", label: "🇦🇺 Australia (+61)" },
  { value: "+81", label: "🇯🇵 Japan (+81)" },
  { value: "+49", label: "🇩🇪 Germany (+49)" },
  { value: "+33", label: "🇫🇷 France (+33)" },
  { value: "+39", label: "🇮🇹 Italy (+39)" },
  { value: "+7", label: "🇷🇺 Russia (+7)" },
  { value: "+86", label: "🇨🇳 China (+86)" },
  { value: "+34", label: "🇪🇸 Spain (+34)" },
  { value: "+55", label: "🇧🇷 Brazil (+55)" },
  { value: "+27", label: "🇿🇦 South Africa (+27)" },
  { value: "+82", label: "🇰🇷 South Korea (+82)" },
  { value: "+60", label: "🇲🇾 Malaysia (+60)" },
  { value: "+65", label: "🇸🇬 Singapore (+65)" },
  { value: "+94", label: "🇱🇰 Sri Lanka (+94)" },
  { value: "+880", label: "🇧🇩 Bangladesh (+880)" },
];
